export const API_ENDPOINTS = {
  auth: {
    login: '/vmanagement/auth/phone',
    logout: '/vid/api/auth/logout',
    logout_all: '/vid/api/auth/logout/all',
    code_challenge: '/vid/api/auth/code/exchange',
    check_password: '/vid/api/users/me/password/checking',
    check_session: '/vid/ajax/auth/me',
    get_shop_v2: '/vshop/shops/v2/me',
  },
  user: {
    get_users: '/vshop/users/me',
    list_profile: '/vshop/users/profiles/me',
  },
  shops: {
    get_shop: '/vshop/shops/me',
  },
  pick_lists: {
    search: '/vshop/configuration/pick-list/search',
    create: '/vshop/configuration/pick-list',
    update: '/vshop/configuration/pick-list',
    delete: '/vshop/configuration/pick-list/{pickListCode}',
    get_by_code: '/vshop/configuration/pick-list/{pickListCode}',
  },
  property: {
    search: '/vshop/configuration/property/search',
    search_all: '/vshop/configuration/property/list',
    create: '/vshop/configuration/property/',
    update: '/vshop/configuration/property/',
    delete: '/vshop/configuration/property/{propertyCode}',
    get_details: '/vshop/configuration/property/{propertyCode}',
  },
  configuration_management: {
    project: '/vshop/forms/',
    category: '/vshop/form/property/types',
    pick_lists: '/vshop/pick-lists',
    property_list: '/vshop/form/properties',
    project_form_export: '/vshop/forms/export',
  },
  form: {
    search: '/vshop/configuration/forms/search',
    create: '/vshop/configuration/forms/',
    update: '/vshop/configuration/forms/',
    get_form_list: '/vshop/configuration/forms',
    get_form_detail: '/vshop/configuration/forms/{formCode}',
    delete: '/vshop/configuration/forms/{formCode}',
    export_form_by_form_code: '/vshop/configuration/forms/export/{formCode}',
  },
  project_management: {
    get_list_project: '/vshop/projects',
    create: '/vshop/projects',
    search: '/vshop/projects/search',
    detail: '/vshop/projects/{projectCode}',
    delete: '/vshop/projects/{projectCode}',
    update: '/vshop/projects',
  },
  workflow: {
    search: '/vshop/workflows/search',
    create: '/vshop/workflows',
    detail: '/vshop/workflows/{workflowCode}',
    delete: '/vshop/workflows/{workflowCode}',
    update: '/vshop/workflows',
  },
  inventory_warehouse: {
    search: '/vshop/inventory-warehouse/search',
    create: '/vshop/inventory-warehouse',
    update: '/vshop/inventory-warehouse',
    delete: '/vshop/inventory-warehouse/{inventoryWarehouseCode}',
    get_detail: '/vshop/inventory-warehouse/{inventoryWarehouseCode}',
  },
  category: {
    data_types: '/vshop/configuration/data-type',
    estate_types: '/vshop/estate-types/',
    provinces: '/chb/address/provinces',
    districts: '/chb/address/provinces/{provinceCode}/districts',
    wards:
      '/chb/address/provinces/{provinceCode}/districts/{districtCode}/wards',
    investors: '/vland/investors',
    app_params: '/chb/app/params',
  },
  inventory: {
    get_detail: '/vshop/inventories/{inventoryCode}',
    search: '/vshop/inventories/search',
    create: '/vshop/inventories',
    update: '/vshop/inventories',
    delete: '/vshop/inventories/{inventoryCode}',
    import_excel_form: '/vshop/excel/import',
    review_inventories_file: '/vshop/inventories/review/',
    upload_inventories_file: '/vshop/inventories/upload/',
    submit_inventories_file: '/vshop/inventories/submit/',
  },
  common: {
    upload_file: '/vshop/attachments/me/upload',
    download_file: '/vshop/files/download',
    delete_file: '/vshop/attachments/me/{attachmentId}',
  },
  files: {
    download_file: '/vshop/attachments/me/{fileId}',
  },
  sales_transactions: {
    search: '/vshop/sales-programs/inventories/search',
    search_inventory_traders:
      '/vshop/sales-transactions/traders/search/{salesProgramDetailCode}',
    update_status: '/vshop/sales-transactions/status',
    confirm_transaction: '/vshop/sales-transactions/confirm',
    enroll: '/vshop/sales-transactions/enroll/{salesProgramDetailCode}',
    admin_approve_request: '/vshop/sales-transactions/approve',
  },
  sales_programs: {
    search: '/vshop/sales-programs/search',
    create: '/vshop/sales-programs',
    update: '/vshop/sales-programs',
    get_details: '/vshop/sales-programs/{salesProgramCode}',
    delete: '/vshop/sales-programs/{salesProgramCode}',
    delete_inventory:
      '/vshop/sales-programs/inventories/{salesProgramDetailCode}',
    approval_request: '/vshop/sales-programs/status',
    search_inventories: '/vshop/sales-programs/inventories/search',
    add_inventories_to_program: '/vshop/sales-programs/inventories',
    admin_approve_request: '/vshop/sales-programs/approval',
  },
  departments: {
    search: '/vshop/departments/search',
    search_availble_employees: '/vshop/employees/departments',
    create: '/vshop/departments',
    update: '/vshop/departments',
    get_details: '/vshop/departments/{departmentCode}',
    delete: '/vshop/departments/{departmentCode}',
    add_employees: '/vshop/departments/employees',
  },
  employees: {
    search: '/vshop/employees/search',
    create: '/vshop/employees',
    update: '/vshop/employees',
    get_details: '/vshop/employees/{employeeCode}',
    delete: '/vshop/employees/{employeeCode}',
    get_user_cms: '/vshop/employees/user-vars/{phone}',
    update_status: '/vshop/employees/status',
    invite_user: '/vshop/employees/invite',
    get_logs: '/vshop/employees/logs',
    get_status: '/vshop/employees/status/{employeeCode}',
  },
  roles: {
    search: '/vshop/roles/search',
    create: '/vshop/roles',
    update: '/vshop/roles',
    get_details: '/vshop/roles/{roleCode}',
    delete: '/vshop/roles/{roleCode}',
  },
  customer: {
    search: '/vshop/customers/search',
    create: '/vshop/customers',
    update: '/vshop/customers',
    get_details: '/vshop/customers/{customerCode}',
    delete: '/vshop/customers/{customerCode}',
    get_logs: '/vshop/customers/logs',
    add_tags: '/vshop/customers/tags',
    add_inventories_interested: '/vshop/customers/inventory-interested',
    add_staff_in_charge: '/vshop/customers/staff-in-charge',
    get_inventories_interested: '/vshop/customers/inventory-interested',
    delete_inventories_interested:
      '/vshop/customers/inventory-interested/{customerCode}',
    update_customer_status: '/vshop/customers/status',
    upload_customer_file: '/vshop/customers/upload',
    upload: '/vshop/customers/upload',
    submit_file: '/vshop/customers/submit/',
    get_customer_merge: '/vshop/customers/search-merge',
    get_customer_table_view: '/vshop/customers/search-v2',
    download_customers: '/vshop/customers/download/BM2',
  },
  tags: {
    search: '/vshop/tags/search',
    create: '/vshop/tags',
    update: '/vshop/tags',
    delete: '/vshop/tags/{tagCode}',
  },
  task: {
    search: '/vshop/tasks/search',
    search_available_employees: '/vshop/employees/tasks',
    create: '/vshop/tasks',
    update: '/vshop/tasks',
    get_details: '/vshop/tasks/{taskCode}',
    delete: '/vshop/tasks/{taskCode}',
    get_tasks_logs: '/vshop/tasks/logs',
    assign_employee: '/vshop/tasks/assign',
    get_parent_tasks: '/vshop/tasks/parent/search',
    get_task_comments: '/vshop/tasks/comments/search',
    create_task_comment: '/vshop/tasks/comments',
    get_tasks_kanban: '/vshop/tasks/kanban/search',
    get_comments_task_latest: '/vshop/tasks/comments/latest',
    change_rank_mode_kanban: '/vshop/tasks/rank',
  },
  jobType: {
    search: '/vshop/jobtypes/search/',
    create: '/vshop/jobtypes',
    update: '/vshop/jobtypes',
    get_details: '/vshop/jobtypes/{jobTypeCode}',
    delete: '/vshop/jobtypes/{jobTypeCode}',
  },
};
